# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-cherry-pick-source

on:
  pull_request:
    branches:
      - main
    types:
      # - opened        # For testing
      # - synchronize   # For testing
      # - reopened      # For testing
      - closed          # Final Usage
  # push:
  #   branches:
  #     - main

jobs:
  detect-change:
    runs-on: ubuntu-latest
    outputs:
      SCRIPT_CHANGE: ${{ steps.filter.outputs.script }}
      DOCUMENT_CHANGE: ${{ steps.filter.outputs.document }}
      WORKFLOW_CHANGE: ${{ steps.filter.outputs.workflow }}
    steps:
      - name: Check Contexts
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.head.ref = ${{ github.event.pull_request.head.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.event.before = ${{ github.event.before }}"
          echo "github.sha = ${{ github.sha }}"
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Get the GitHub App's Token
        id: ggat
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Filter Changes in the Pull Request
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ steps.ggat.outputs.token }}
          filters: |
            script:
              - 'cmake/modules/GitUtils.cmake'
              - 'cmake/scripts/*.cmake'
              - 'cmake/templates/*'
              - '.gitattributes'
              - '.gitignore'
              - '.gitmodules'
              - 'CMakeLists.txt'
              - 'CMakePresets.json'
              - 'languages.json'
            document:
              - 'docs/ACKNOWLEDGEMENTS.md'
              - 'docs/CONTRIBUTING.md'
              - 'docs/MAINTAINING.md'
              - 'README.md'
            workflow:
              - '.github/workflows/matrix.json'
              - '.github/workflows/*.yml'
      - name: Check Outputs of paths-filter
        run: |
          echo "steps.filter.outputs.script   = ${{ steps.filter.outputs.script }}"
          echo "steps.filter.outputs.document = ${{ steps.filter.outputs.document }}"
          echo "steps.filter.outputs.workflow = ${{ steps.filter.outputs.workflow }}"
          echo "steps.filter.outputs.script_count   = ${{ steps.filter.outputs.script_count }}"
          echo "steps.filter.outputs.document_count = ${{ steps.filter.outputs.document_count }}"
          echo "steps.filter.outputs.workflow_count = ${{ steps.filter.outputs.workflow_count }}"

  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.rvm.outputs.VERSION }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Read VERSION from matrix.json
        id: rvm
        run: |
          FILTER=".include | map(.VERSION)"
          VERSION=$(jq -c "$FILTER" .github/workflows/matrix.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION:"
          echo "$VERSION" | jq "."

  cherry-pick-source:
    needs: [ 'detect-change', 'get-matrix' ]
    if: (needs.detect-change.outputs.SCRIPT_CHANGE   != 0) ||
        (needs.detect-change.outputs.WORKFLOW_CHANGE != 0)
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        VERSION: ${{ fromJson(needs.get-matrix.outputs.VERSION) }}
      fail-fast: false
    steps:
      - name: Check Contexts
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.head.ref = ${{ github.event.pull_request.head.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.event.before = ${{ github.event.before }}"
          echo "github.sha = ${{ github.sha }}"
          echo "[Secrets]"
          echo "secrets.APP_ID = ${{ secrets.APP_ID }}"
          echo "secrets.APP_PRIVATE_KEY = ${{ secrets.APP_PRIVATE_KEY }}"
      - name: Get the GitHub App's Token
        uses: tibdex/github-app-token@v2
        id: ggat
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          # token: ${{ steps.ggat.outputs.token }}
      - name: Cherry Pick into 'source/${{ matrix.VERSION }}' branch
        uses: carloscastrojumo/github-cherry-pick-action@v1.0
        with:
          token: ${{ steps.ggat.outputs.token }}
          branch: 'source/${{ matrix.VERSION }}'
          labels: 'cherry-pick, automerge'
          force: true
          title: |
            [cherry-pick] {old_title}
          body: |
            Cherry picking #{old_pull_request_id} onto this branch
